### PR TITLE
Format ChatGPT response for slack

### LINKED ISSUE #323: update chatgpt prompt to append "format all responses for slack"
title

### PR DESCRIPTION
**Pull request by wiz0floyd**
Fixes #323

### CODE REVIEW

**Comment by chelming** [comment]
do we have an example of a bad one? is it that slack isn't formatting it right or that we're not including markdown as the block type?

**Comment by wiz0floyd** [comment]
Anything with BOLD text doesn't get formatted right. It does ** instead of *. @chelming

**Comment by Lacah** [comment]
@wiz0floyd is this still relevant and if so, OK to be reviewed?

**Comment by wiz0floyd** [comment]
I haven't figured out the prompt to get it to use slack markdown correctly
so we can close this and open an issue.

**Pull request closed without merging**
