### PR TITLE
Creates !ice breaker parser

### LINKED ISSUE #74: Create an !ice breaker parser
something like: when someone says !ice breaker, the bot responds with a random "get to know each other" prompt.
example responses
- how many siblings do you have, 
- what's your favorite movie, 
- what do you do for fun, 
- would you rather fight 100 duck-sized horses or 1 horse-sized duck?

### PR DESCRIPTION
**Pull request by DavidMarcial**
This pull request creates the ice breaker file and parser. Added a few ice breakers but more could be added. Closes #74

### CODE REVIEW

**Comment by earlduque** [comment]
I guess this same thing could be solved via slackbot, so in the future it might be worth exploring how we can attach this to an api or make it more dynamic. thanks for making this, regardless!

**Comment by DavidMarcial** [comment]
@earlduque What do you mean that it could be solved via slackbot?

**Comment by earlduque** [comment]
https://slack.com/resources/using-slack/a-guide-to-slackbot-custom-responses

Simple call and responses can be configured directly within a slack server by any member.

Usually we tend to deprecate Slacker parsers that can be converted to simple Slackbot custom responses since it's less overhead. Slacker tends to be the parsers that are more complex or require some programing to get the response we are hoping for.

**Comment by DavidMarcial** [comment]
@earlduque Hey I updated the ice breaker to use the slackbot custom response. I included the screen shot and hope that is what you intended me to do when you shared the link above. 
Screenshot 2023-10-30 at 10 15 49 PM

**Pull request merged**
