### PR TITLE
React to Utah.js

### LINKED ISSUE #197: Add a parser that reacts with the :utah: emoji when the channel #utah is mentioned

### PR DESCRIPTION
**Pull request by Ladirinia**
Hopefully resolves #197 !

### CODE REVIEW

**Comment by Ladirinia** [comment]
Hi, I noted I used send_chat rather than send_reaction and would try to update / send a new pull request.

**Comment by earlduque** [comment]
You can either let us know when you're done, we can use the same PR!

Also, don't you want to wait til Oct1 so you can get Hacktoberfest credit?

**Comment by Ladirinia** [comment]
I'm done :D

**Comment by Ladirinia** [comment]
I'll go without the credit, otherwise I would have to be patient for a whole day :D

**Comment by earlduque** [comment]
Haha if you say so, looks good to go. approved!

I'm actually interested to see if this will work because if someone says #utah in the chat, i'm not sure if it stays as "#utah" by the time it gets to the parser, slack might change it to the channel unique ID by then. If it doesn't work, i'll create another issue for it.

Also, created #214 to match this for vancouver

**Comment by earlduque** [comment]
Yep, my guess was right. Slack doesn't actually keep it as the word utah when it's talking about a channel:

image

I'll create some issues to change it, i think it's okay if we make it say the word, instead of the channel

**Pull request merged**
