### PR TITLE
Create Corporate Joke

### PR DESCRIPTION
**Pull request by ankitshu**
Implemented a corporate jokes parser using the Chuck Norris Jokes API. The parser identifies corporate jokes based on user input and returns a relevant joke. Incorporated error handling for cases where no matching joke is found.

### CODE REVIEW

**Comment by Lacah** [comment]
@ankitshu thanks for the great contribution. Please note that your Slackerbot parsers should actually be of .js extension. I have changed your file accordingly this time, but please keep this in mind for future PRs.
Thanks!

**Comment by Lacah** [comment]
@ankitshu I have tested it in the #slacker-dev-public channel on SNDevs Slack and it didn't work. Do we actually need an API key? It is mentioned as a comment but I saw no variable. Could you please look into it? Thanks.

**Comment by ankitshu** [comment]
@Lacah  I just checked they "Chuck Lorris " do not have jokes with the word corporate hence must not be returning a value, Can we change that to celebrity Jokes, I can create an another pull request if required. Also it does not require any key

**Comment by Lacah** [comment]
Thanks for checking. I thought the error handling would take care of those scenarios ;)
Anyway, if you could have a look and test it, would be great.
Feel free to open a new PR with the fix. 
Thanks!

**Pull request merged**
