### PR TITLE
Add GitHub !issue parser

### LINKED ISSUE #292: Create !issue to create github issues
!issue "some issue" should create a github issue for this repo

### PR DESCRIPTION
**Pull request by SapphicFire**
## Description
#292 described a need to create a parser that can create GitHub issues from Slack. This PR includes this parser, and contains support for a GitHub App, [SNDevs Slacker Issue Reporter](https://github.com/apps/sndevs-slacker-issue-reporter).

Resolves #292 

## Usage

```
!issue [repo name or shorthand] description
```

Example:
```
!issue Slacker Add a new issue
```

The description will be placed in both the title and body, with the title shortened if it overruns a character limit (currently 60)

## Set up
In order to activate the `!issue` parser, the following steps must occur

### On GitHub:
- [x] Request the install of [SNDevs Slacker Issue Reporter](https://github.com/apps/sndevs-slacker-issue-reporter) in the ServiceNow Dev Program Organisation
- [x] Approve the above install request (@earlduque or other Owner of org)

### On DPR:
- [x] Create `slackerbot.issueapp.install_id` property with app installation ID in the Global scope
- [x] Create `slackerbot.issueapp.id` property with app client ID in the Global scope
- [x] Create `sys_certificate` record and attach JKS trust store
- [x] Create `jwt_keystore_aliases` record and associate above X.509 Certificate record
- [x] Create `jwt_provider` record and associate above JWT Key record
- [x] Create `slackerbot.issueapp.provider` property with sys_id of above JWT Provider record
- [x] Verify cross-scope privileges and module access policies apply correctly on first use

### CODE REVIEW

**Comment by SapphicFire** [comment]
I have organised the configuration on the DPR side with the exception of the installation ID as we won't know that until the install request is approved.

**Comment by chelming** [comment]
should all cases of `!issue Slacker` be replaced with `!issue SlackerBot`?

**Comment by earlduque** [comment]
we good. you rock

**Comment by chelming** [comment]
can the app owner be set to an org or does that take some sort of certification/review?

**Pull request merged**
